services:
  - type: web
    name: work-shift-scheduler
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: workshiftdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: work-shift-scheduler.onrender.com,localhost,127.0.0.1
    autoDeploy: true
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1

databases:
  - name: workshiftdb
    plan: free